// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJtdbahTVwI_rWVf11UgV4YCcdhM-6Xrc',
    appId: '1:835866235233:web:23f9df471b0566329af520',
    messagingSenderId: '835866235233',
    projectId: 'dalel-4c033',
    authDomain: 'dalel-4c033.firebaseapp.com',
    storageBucket: 'dalel-4c033.appspot.com',
    measurementId: 'G-E7T6V9R16V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOtYtqBmD0sGDZO86u0emGSyAPgJvbYYY',
    appId: '1:835866235233:android:edeb368993aae08a9af520',
    messagingSenderId: '835866235233',
    projectId: 'dalel-4c033',
    storageBucket: 'dalel-4c033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Jr0i7DS1fHXnbA4glbXf-LcUgA5DOCg',
    appId: '1:835866235233:ios:79da8c8e153421369af520',
    messagingSenderId: '835866235233',
    projectId: 'dalel-4c033',
    storageBucket: 'dalel-4c033.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Jr0i7DS1fHXnbA4glbXf-LcUgA5DOCg',
    appId: '1:835866235233:ios:cc8658a42fca6a119af520',
    messagingSenderId: '835866235233',
    projectId: 'dalel-4c033',
    storageBucket: 'dalel-4c033.appspot.com',
    iosBundleId: 'com.example.dalel.RunnerTests',
  );
}
